[package]
name = "automata-contract-tests"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ckb-testtool.workspace = true
ckb-hash.workspace = true
ckb-system-scripts.workspace = true
molecule.workspace = true
serde.workspace = true
serde_json.workspace = true
