import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { format } from "prettier";

const compilerVersion = "0.9.2";
const checkOnly = process.argv.slice(2).includes("--check");
const root = new URL("../", import.meta.url);
const schemaUrl = new URL("contracts/schemas/job_v1.mol", root);
const rustUrl = new URL("contracts/generated/job_v1.rs", root);
const typescriptUrl = new URL("packages/molecule/src/generated/job_v1.ts", root);

const compilerOutput = execFileSync("moleculec", ["--version"], {
  encoding: "utf8",
}).trim();
assert.equal(
  compilerOutput,
  `Moleculec ${compilerVersion}`,
  `expected moleculec ${compilerVersion}`,
);

const schemaText = (await readFile(schemaUrl, "utf8")).replaceAll("\r\n", "\n");
const schemaHash = createHash("sha256").update(schemaText).digest("hex");
const compilerIr = JSON.parse(
  execFileSync(
    "moleculec",
    ["--language", "-", "--format", "json", "--schema-file", fileURLToPath(schemaUrl)],
    { encoding: "utf8" },
  ),
);

function typescriptCodec(type) {
  return type === "byte" ? "number.Uint8" : type;
}

function generateTypescript(declarations) {
  const lines = [
    "// @generated by scripts/generate-schemas.mjs; do not edit.",
    `// Source SHA-256: ${schemaHash}`,
    'import { molecule, number, type PackParam, type UnpackResult } from "@ckb-lumos/codec";',
    "",
    `export const JOB_V1_SCHEMA_SHA256 = "${schemaHash}" as const;`,
    "",
  ];

  for (const declaration of declarations) {
    if (declaration.type === "array") {
      assert.equal(declaration.item, "byte", `${declaration.name} must contain bytes`);
      const integerWidths = { Uint16: 2, Uint32: 4, Uint64: 8 };
      const integerWidth = integerWidths[declaration.name];
      if (integerWidth !== undefined) {
        assert.equal(declaration.item_count, integerWidth);
        lines.push(`export const ${declaration.name} = number.${declaration.name}LE;`);
      } else {
        lines.push(
          `export const ${declaration.name} = molecule.array(number.Uint8, ${declaration.item_count});`,
        );
      }
      continue;
    }

    assert.equal(declaration.type, "table", `unsupported declaration: ${declaration.type}`);
    lines.push(`export const ${declaration.name} = molecule.table(`);
    lines.push("  {");
    for (const field of declaration.fields) {
      lines.push(`    ${field.name}: ${typescriptCodec(field.type)},`);
    }
    lines.push("  },");
    lines.push("  [");
    for (const field of declaration.fields) {
      lines.push(`    "${field.name}",`);
    }
    lines.push("  ],");
    lines.push(");");
    lines.push(`export type ${declaration.name}Value = UnpackResult<typeof ${declaration.name}>;`);
    lines.push(`export type ${declaration.name}Like = PackParam<typeof ${declaration.name}>;`);
  }

  return lines.join("\n") + "\n";
}

async function generateRust() {
  const generated = execFileSync(
    "moleculec",
    ["--language", "rust", "--schema-file", fileURLToPath(schemaUrl)],
    { encoding: "utf8" },
  );
  const header = [
    "// @generated by moleculec 0.9.2; do not edit.",
    `// Source SHA-256: ${schemaHash}`,
    `pub const JOB_V1_SCHEMA_SHA256: &str = "${schemaHash}";`,
    "",
  ].join("\n");
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "automata-schema-"));
  const temporaryFile = join(temporaryDirectory, "job_v1.rs");
  try {
    await writeFile(temporaryFile, header + generated.replaceAll("\r\n", "\n"));
    execFileSync("rustfmt", ["--edition", "2024", temporaryFile]);
    return (await readFile(temporaryFile, "utf8")).replaceAll("\r\n", "\n");
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

async function writeOrCheck(url, content) {
  const path = fileURLToPath(url);
  if (checkOnly) {
    const current = (await readFile(url, "utf8")).replaceAll("\r\n", "\n");
    assert.equal(current, content, `${path} is not generated from the current schema`);
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
}

const typescript = await format(generateTypescript(compilerIr.declarations), {
  parser: "typescript",
  endOfLine: "lf",
});
const rust = await generateRust();
await writeOrCheck(typescriptUrl, typescript);
await writeOrCheck(rustUrl, rust);

console.log(
  `${checkOnly ? "Checked" : "Generated"} Rust and TypeScript bindings for ${schemaHash}`,
);
